


class Timeout(object):
    GENERIC_COMMAND= 3.
    MIRROR_GET_STATUS= 3.
    MIRROR_GET_SHAPE= 3.
    MIRROR_SET_SHAPE= 3.
    SPLATT_COMMAND = 10.
    SPLATT_SET = 120.
    MODULATOR_GET_STATUS = 5.
    MODULATOR_SET_RADIUS = 20.
    MODULATOR_SET_FREQUENCY = 20.
    MODULATOR_SET_CENTER = 20.
    MODULATOR_GET_DIAGNOSTIC_DATA = 20.
